name: veloprime_hybrid_app
description: Lokalny klient hybrydowy CRM VeloPrime dla Windows i Android.
publish_to: none
version: 0.1.15+32

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.6.0
  file_selector: ^1.0.3
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.13

msix_config:
  display_name: VeloPrime CRM
  publisher_display_name: VeloPrime
  identity_name: pl.veloprime.crm
  msix_version: 0.1.15.25
  logo_path: assets/branding/app_icon.png
  certificate_path: deploy/msix/certs/veloprime-crm-test-build.pfx
  trim_logo: false
  capabilities: internetClient
  architecture: x64
  store: false
  build_windows: true
  publisher: CN=VeloPrime CRM Test
  app_installer:
    publish_folder_path: build\msix\publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo.png
    - assets/branding/app_icon.png
    - assets/backgrounds/
    - assets/offers/asset_manifest.json
    - assets/offers/grafiki/
    - assets/offers/grafiki/byd-atto-2/
    - assets/offers/grafiki/byd-dolphin-surf/
    - assets/offers/grafiki/Seal/
    - assets/offers/grafiki/Seal 5/
    - assets/offers/grafiki/Seal 6 touring/
    - assets/offers/grafiki/Seal 7/
    - assets/offers/grafiki/seal-6-dmi/
    - assets/offers/grafiki/Seal-U/
    - assets/offers/spec/